import type { NotionItem } from "./types";

export const MOCK_ITEMS: NotionItem[] = [
  {
    id: "MN-PLT-001",
    title: "Place to Be",
    icon: "📄",
    cover:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDixMSYgCrD8QKhI1_qtBAQMD3PXlJzP8Kd5dNYfebZydA37Q7zDlF-JaHb2lnXupXz-xKq_Ja8JV8YoB0CO0emQwqxLrLaoK8SjCQ8u_Fsvwvmz6AGRYWYt87uI-bNLQYM9kJVKEndVV5hIoM3HdAxnoxCrBDFsSyb1qV5RsS-U-T9CtcdiiRmWXgz-G4-d_w93ruZrra5yfjChTtwhe3JyPczT4dEAsMqhYMRVbBPiT__6t3wdTW7OLZEgVehcVIh9Es",
    initials: "PTB",
    status: "Reading/Watching",
    statusColor: "purple",
    tipe: "Manhwa",
    tipeColor: "brown",
    tags: [
      { name: "BL", color: "green" },
      { name: "Comedy", color: "purple" },
      { name: "Romance", color: "orange" },
    ],
    createdTime: "2026-09-26T22:30:00.000Z",
    lastEditedTime: "2026-09-26T22:30:00.000Z",
    createdBy: {
      name: "arya",
    },
    link: "https://www.mangago.me/read-manga/place_to_be_1/",
    rawAltLink: null,
    notes: "",
  },
  {
    id: "MN-ORV-002",
    title: "Omniscient Reader's Viewpoint",
    icon: "📖",
    cover: null,
    initials: "ORV",
    status: "Reading/Watching",
    statusColor: "purple",
    tipe: "Manhwa",
    tipeColor: "brown",
    tags: [
      { name: "Action", color: "gray" },
      { name: "Fantasy", color: "gray" },
    ],
    createdTime: "2026-09-25T20:15:00.000Z",
    lastEditedTime: "2026-09-26T21:20:00.000Z",
    createdBy: {
      name: "arya",
    },
    link: "https://asurascans.com/orv",
    rawAltLink: "https://webtoons.com/...",
    notes: "Ch. 210 Epilogue Arc",
  },
  {
    id: "MN-SL-003",
    title: "Solo Leveling",
    icon: "🗡️",
    cover: null,
    initials: "SL",
    status: "Completed",
    statusColor: "green",
    tipe: "Manhwa",
    tipeColor: "brown",
    tags: [
      { name: "Action", color: "gray" },
      { name: "Supernatural", color: "gray" },
    ],
    createdTime: "2026-08-14T14:00:00.000Z",
    lastEditedTime: "2026-09-10T11:15:00.000Z",
    createdBy: {
      name: "arya",
    },
    link: "https://tapas.io/series/solo-leveling",
    rawAltLink: "https://kakao.page/...",
    notes: "Tamat 200 Ch + Side Story",
  },
  {
    id: "MN-FRI-004",
    title: "Sousou no Frieren",
    icon: "🪄",
    cover: null,
    initials: "FRI",
    status: "Reading/Watching",
    statusColor: "purple",
    tipe: "Manga",
    tipeColor: "zinc",
    tags: [
      { name: "Adventure", color: "gray" },
      { name: "Fantasy", color: "gray" },
    ],
    createdTime: "2026-09-18T16:30:00.000Z",
    lastEditedTime: "2026-09-24T19:45:00.000Z",
    createdBy: {
      name: "arya",
    },
    link: "https://mangadex.org/title/frieren",
    rawAltLink: null,
    notes: "Ch. 128 On-going",
  },
  {
    id: "MN-LKM-005",
    title: "Lookism",
    icon: "🥋",
    cover: null,
    initials: "LKM",
    status: "Reading/Watching",
    statusColor: "purple",
    tipe: "Manhwa",
    tipeColor: "brown",
    tags: [
      { name: "Action", color: "gray" },
      { name: "Drama", color: "gray" },
    ],
    createdTime: "2026-07-12T11:00:00.000Z",
    lastEditedTime: "2026-09-22T18:10:00.000Z",
    createdBy: {
      name: "arya",
    },
    link: "https://webtoons.com/lookism",
    rawAltLink: "https://naver.com/...",
    notes: "Workers Arc",
  },
  {
    id: "MN-CSM-006",
    title: "Chainsaw Man",
    icon: "⛓️",
    cover: null,
    initials: "CSM",
    status: "Reading/Watching",
    statusColor: "purple",
    tipe: "Manga",
    tipeColor: "zinc",
    tags: [
      { name: "Action", color: "gray" },
      { name: "Dark", color: "gray" },
    ],
    createdTime: "2026-06-05T21:30:00.000Z",
    lastEditedTime: "2026-09-20T15:00:00.000Z",
    createdBy: {
      name: "arya",
    },
    link: "https://mangaplus.shueisha.co.jp/...",
    rawAltLink: null,
    notes: "Part 2 School arc",
  },
  {
    id: "MN-TOG-007",
    title: "Tower of God",
    icon: "👑",
    cover: null,
    initials: "TOG",
    status: "On Hold",
    statusColor: "yellow",
    tipe: "Manhwa",
    tipeColor: "brown",
    tags: [
      { name: "Fantasy", color: "gray" },
      { name: "Mystery", color: "gray" },
    ],
    createdTime: "2026-05-01T13:15:00.000Z",
    lastEditedTime: "2026-08-28T22:00:00.000Z",
    createdBy: {
      name: "arya",
    },
    link: "https://webtoons.com/tower-of-god",
    rawAltLink: null,
    notes: "Season 3 hiatus",
  },
  {
    id: "MN-DDD-008",
    title: "Dandadan",
    icon: "⚡",
    cover: null,
    initials: "DDD",
    status: "Plan to Read",
    statusColor: "blue",
    tipe: "Manga",
    tipeColor: "zinc",
    tags: [
      { name: "Sci-Fi", color: "gray" },
      { name: "Comedy", color: "gray" },
    ],
    createdTime: "2026-09-01T12:45:00.000Z",
    lastEditedTime: "2026-09-25T17:00:00.000Z",
    createdBy: {
      name: "arya",
    },
    link: "https://shonenjumpplus.com/...",
    rawAltLink: null,
    notes: "Anime airing soon",
  },
];
